---
title: "Causal model"
subtitle: "Evaluation, part 3 --- PMAP 8521, Spring 2026"
author: "YOUR NAME HERE"  # Replace with your actual name
date: "DATE GOES HERE"  # Replace with the date
date-format: "long"
format:
  html:
    toc: true
  typst:
    toc: true
  pdf:
    toc: true
  docx:
    toc: true
---


**Feel free to remove any/all of the placeholder text and instructions here!**

::: {.callout-tip title="Inserting DAG images"}
You'll need to include images in this assignment, similar to what you did with the background and theory assignment.

You can export figures from dagitty and include them here, or you can use R to draw the DAGs. 

See the assignment instruction page for hints and sample code.
:::

# Task 1: DAG from a news article

## Part 1: Implicit DAG

Find a recent news article that makes a causal claim and interpret that claim by drawing an appropriate diagram *of the claim they make* with any evidence they provide in the article.

Summarize the causal claim. Describe what the authors controlled for (if anything). Explain your version of their implicit DAG here. Justify the inclusion of each node (point) and connection (line) in the graph. *(≈150 words)*

INCLUDE IMAGE HERE

## Part 2: Better DAG

The article likely omitted some confounders or included some colliders or did (or didn't do) something else that casts doubt on the causal claim. 

Create a second, better DAG of the same causal claim. Describe what *you* think should be included in the DAG to model the data generating process. Justify the inclusion of each node (point) and connection (line) in the graph. Identify which nodes need to be controlled for or adjusted to close backdoor paths and identify/isolate the causal effect. *(≈200 words)*

INCLUDE IMAGE HERE


# Task 2: DAG for your program

Identify **one** (1) outcome that you're most interested in from your final project program. Draw a DAG that shows the causal effect of your program's intervention on the outcome. **You just need one ideal DAG here.**

Describe what *you* think should be included in the DAG to model the data generating process. Justify the inclusion of each node (point) and connection (line) in the graph. Identify which nodes need to be controlled for or adjusted to close backdoor paths and identify/isolate the causal effect. *(≈200 words)*

INCLUDE IMAGE HERE
