---
title: "Cholera"
date: "2026-03-12"
date-format: "long"
format:
  html:
    toc: true
---

```{r}
#| warning: false
#| message: false

library(tidyverse)
library(parameters)

# This way lets you specify tables row-wise (hence t*r*ibble) and is far easier to read
cholera <- tribble(
  ~deaths , ~year , ~location              ,
     1349 ,  1849 , "Southwark & Vauxhall" ,
      847 ,  1849 , "Lambeth"              ,
     1466 ,  1854 , "Southwark & Vauxhall" ,
      193 ,  1854 , "Lambeth"
) |>
  mutate(year = factor(year)) |>
  mutate(location = fct_relevel(location, "Southwark & Vauxhall"))

model <- lm(
  deaths ~ year + location + year * location,
  data = cholera
)
```

```{r}
model_parameters(model)
```

```{r}
results <- model_parameters(model)

before_treatment <-
  results |>
  filter(Parameter == "(Intercept)") |>
  pull(Coefficient) +
  results |>
    filter(Parameter == "locationLambeth") |>
    pull(Coefficient)

year_effect <- results |>
  filter(Parameter == "year1854") |>
  pull(Coefficient)

after_treatment <- before_treatment + year_effect

dd_effect <- results |>
  filter(Parameter == "year1854:locationLambeth") |>
  pull(Coefficient)

ggplot(cholera, aes(x = year, y = deaths, color = location)) +
  geom_line(aes(group = location)) +
  annotate(
    geom = "segment",
    x = "1849",
    xend = "1854",
    y = before_treatment,
    yend = before_treatment + year_effect,
    linetype = "dashed",
    color = "grey50"
  ) +
  annotate(
    geom = "segment",
    x = "1854",
    xend = "1854",
    y = after_treatment,
    yend = before_treatment + year_effect + dd_effect,
    linetype = "dotted",
    color = "blue"
  )
```
