---
title: "Happiness"
date: "2026-03-12"
date-format: "long"
format:
  html:
    toc: true
---

```{r}
#| warning: false
#| message: false

library(tidyverse)
library(parameters)
library(marginaleffects)

world_happiness <- read_csv("data/world_happiness.csv") |> 
  mutate(latin_america = region == "Latin America & Caribbean")
```

# Indicator variables

```{r}
model_life_school_region <- lm(
  happiness_score ~ life_expectancy + school_enrollment + region, 
  data = world_happiness
)

model_parameters(model_life_school_region)
avg_comparisons(model_life_school_region)
predictions(model_life_school_region, newdata = datagrid(region = unique))
```

```{r}
model_life_school_la <- lm(
  happiness_score ~ life_expectancy + latin_america,
  data = world_happiness
)
model_parameters(model_life_school_la)
```

```{r}
ggplot(world_happiness, aes(x = life_expectancy, y = happiness_score)) +
  geom_point(aes(color = latin_america)) +
  geom_abline(
    slope = 0.1023494,
    intercept = -2.0770858,
    color = "blue",
    linewidth = 2
  ) +
  geom_abline(
    slope = 0.1023494,
    intercept = -2.0770858 + 0.6234255,
    color = "orange",
    linewidth = 2
  )
```

```{r}
plot_predictions(
  model_life_school_la,
  condition = c("life_expectancy", "latin_america"),
  points = 0.5
)
```

```{r}
model_life_school_la_int <- lm(
  happiness_score ~
    life_expectancy + latin_america + life_expectancy * latin_america,
  data = world_happiness
)
model_parameters(model_life_school_la_int)
avg_comparisons(model_life_school_la_int, by = "latin_america")
avg_slopes(model_life_school_la_int, by = "latin_america", variables = "life_expectancy")
```

```{r}
ggplot(world_happiness, aes(x = life_expectancy, y = happiness_score)) +
  geom_point(aes(color = latin_america)) +
  geom_abline(
    slope = 0.10154408,
    intercept = -2.01948544,
    color = "blue",
    linewidth = 2
  ) +
  geom_abline(
    slope = 0.10154408 + 0.02884127,
    intercept = -2.01948544 + -1.51554651,
    color = "darkred",
    linewidth = 2
  )
```

```{r}
plot_predictions(
  model_life_school_la_int,
  condition = c("life_expectancy", "latin_america"),
  points = 0.5
)
```

```{r}
model_life_school_int <- lm(
  happiness_score ~ life_expectancy * region,
  data = world_happiness
)
model_parameters(model_life_school_int)
avg_slopes(model_life_school_int, by = "region", variables = "life_expectancy")

plot_predictions(
  model_life_school_int,
  condition = c("life_expectancy", "region"),
  points = 0.5
)
```
