---
title: "Penguins and interactions"
date: "2025-03-06"
date-format: "long"
format:
  html:
    toc: true
  pdf:
    toc: true
  docx:
    toc: true
---

```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(broom)
library(parameters)
library(marginaleffects)
library(palmerpenguins)

penguins <- penguins |> drop_na(sex)
```


```{r}
model_basic <- lm(
  body_mass_g ~ flipper_length_mm + species,
  data = penguins
)

# With broom
tidy(model_basic)

# With parameters
model_parameters(model_basic)

# With marginaleffects
avg_comparisons(model_basic)
```


```{r}
basic_predictions <- predictions(model_basic)

ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species), alpha = 0.4) +
  geom_smooth(data = basic_predictions, aes(y = estimate, color = species))
```


```{r}
model_interaction <- lm(
  body_mass_g ~ flipper_length_mm * species,
  data = penguins
)

# With broom
tidy(model_interaction)

# With parameters
model_parameters(model_interaction)

# With marginaleffects
avg_comparisons(model_interaction, by = "species")
```


```{r}
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species), alpha = 0.4) +
  geom_smooth(aes(color = species), method = "lm", se = FALSE)
```

```{r}
interaction_predictions <- predictions(model_interaction)

ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species), alpha = 0.4) +
  geom_smooth(data = interaction_predictions, aes(y = estimate, color = species))
```
